### ISSUE TITLE
How to "Visualize the data"?

### ISSUE THREAD

**Issue by sneedgers** [sun1638650145/CRNN#4]
Hello im trying to visualize data
![image](https://user-images.githubusercontent.com/107140768/183304168-0d576b60-e721-47b7-8af6-2dcb38922ebc.png)

like that but I cant figure how to get the name itself ?
![image](https://user-images.githubusercontent.com/107140768/183304237-ac72c58e-7923-49e7-a8ef-72bfe593f860.png)

train_validation_split 
doesnt return names or whatever. I am not sure how to figure it out

**Comment by sneedgers** [comment]
![image](https://user-images.githubusercontent.com/107140768/183304608-7b30843a-76b0-4dc7-8c29-45b1bfc9b532.png)
![image](https://user-images.githubusercontent.com/107140768/183304620-cc6da508-3689-4e77-9a66-b1fa6ed0207e.png)

this is what I did to use the model

**Comment by sneedgers** [comment]
How do I visualise in the jupyter notebook?

**Comment by sun1638650145** [comment]
First of all, I'm sorry I didn't implement the visualization function. If you want to use the visualization function, you can use this function from `from CRNN.tools import create_dataset`, create a `tf.data.Dataset` and use `matplotlib` for visualization. 
Second, the file name is the label, although it is randomly scrambled, the image and label are corresponding.

**Comment by sneedgers** [comment]
> First of all, I'm sorry I didn't implement the visualization function. If you want to use the visualization function, you can use this function from `from CRNN.tools import create_dataset`, create a `tf.data.Dataset` and use `matplotlib` for visualization. Second, the file name is the label, although it is randomly scrambled, the image and label are corresponding.

Can you help me with that ? I am really bad with matplotlib and tuples or whatever I am not really a developer 
I just scrap data and images for large datasets

**Comment by sneedgers** [comment]
Bump 
<3

**Comment by sun1638650145** [comment]
@sneedgers You can use this newly developed function for visualization.
```python 
from CRNN.tools import visualize_dataset

visualize_dataset(image_dir='/path/to/your/datasets/')
```
